const dataRoomFacilities = {
  SEPARATE_DINING_AREA: 'Separate Dining Area',
  DINNER: 'Dinner',
  BREAKFAST: 'Breakfast',
  DVD_CD_PLAYER: 'Dvd Cd Player',
  IN_ROOM_SAFE: 'In Room Safe',
  DESK: 'Desk',
  PRIVATE_BATHROOM: 'Private Bathroom',
  BATHTUB: 'Bathtub',
  INHOUSE_MOVIES: 'Inhouse Movies',
  TELEVISION: 'Television',
  MOSQUITO_NET: 'Mosquito Net',
  EXECUTIVE_LOUNGE_ACCESS: 'Executive Lounge Access',
  SHOWER: 'Shower',
  HEATED_WATER: 'Heated Water',
  DAILY_NEWSPAPER: 'Daily Newspaper',
  COFFEE_TEA_MAKER: 'Coffee Tea Maker',
  INTERNET_ACCESS_LAN_CHARGES_APPLY: 'Internet Access Lan Charges Apply',
  SHARED_BATHROOM: 'Shared Bathroom',
  INTERCONNECTING_ROOMS_AVAILABLE: 'Interconnecting Rooms Available',
  WASHING_MACHINE: 'Washing Machine',
  KITCHENETTE: 'Kitchenette',
  SEATING_AREA: 'Seating Area',
  INTERNET_ACCESS_WIFI_COMPLIMENTARY: 'Internet Access Wifi Complimentary',
  REFRIGERATOR: 'Refrigerator',
  LUNCH: 'Lunch',
  INTERNET_ACCESS_WIFI_CHARGES_APPLY: 'Internet Access Wifi Charges Apply',
  DISHWASHER: 'Dishwasher',
  INTERNET_ACCESS_LAN_COMPLIMENTARY: 'Internet Access Lan Complimentary',
  BATHROBES: 'Bathrobes',
  HAIR_DRYER: 'Hair Dryer',
  MICROWAVE: 'Microwave',
  MINI_BAR: 'Mini Bar',
  AIR_CONDITIONING: 'Air Conditioning',
  IN_ROOM_VIDEO_GAMES: 'In Room Video Games',
  CLOTHES_DRYER: 'Clothes Dryer',
  BALCONY_TERRACE: 'Balcony Terrace',
  PRIVATE_POOL: 'Private Pool',
  FAN: 'Fan',
  IRONING_FACILITIES: 'Ironing Facilities',
  BLACKOUT_CURTAINS: 'Blackout Curtains',
  TOILETRIES: 'Toiletries',
  COMPLIMENTARY_BOTTLED_WATER: 'Complimentary Bottled Water',
  NON_SMOKING_ROOMS: 'Non Smoking Rooms',
};
