const dataRegistrationFacilities = {
  SHOPPING_CENTER_SHUTTLE_SURCHARGE: 'Shopping Center Shuttle Surcharge',
  MINIBAR: 'Minibar',
  SUN_LOUNGERS: 'Sun Loungers',
  FULL_BOARD_WITHOUT_DRINKS: 'Full Board Without Drinks',
  BEACH_UMBRELLA: 'Beach Umbrella',
  SEPARATE_SHOWER_AND_TUB: 'Separate Shower And Tub',
  BUSINESS_FACILITY: 'Business Facility',
  OUTDOOR_ACTIVITIES: 'Outdoor Activities',
  WEDDING_SERVICE: 'Wedding Service',
  WIFI_FREE: 'Wifi Free',
  WATERSLIDE: 'Waterslide',
  BREAKFAST_SERVED_TO_THE_TABLE: 'Breakfast Served To The Table',
  INDOOR_POOL: 'Indoor Pool',
  NON_SMOKING_ROOM: 'Non Smoking Room',
  BELLBOY_SERVICE: 'Bellboy Service',
  HAS_24_HOUR_SECURITY: 'Has 24 Hour Security',
  INDOOR_HEATED_POOL: 'Indoor Heated Pool',
  BABYSITTING_SURCHARGE: 'Babysitting Surcharge',
  HAIR_DRYER: 'Hair Dryer',
  CATAMARAN_SAILING: 'Catamaran Sailing',
  LIBRARY: 'Library',
  A_LA_CARTE_LUNCH: 'A La Carte Lunch',
  VOLLEYBALL: 'Volleyball',
  INTERNATIONAL_CALL: 'International Call',
  TV_LOUNGE: 'Tv Lounge',
  HANDBALL: 'Handball',
  DINING_AREA: 'Dining Area',
  CHILDREN_PLAY_AREA: 'Children Play Area',
  AIR_CONDITIONING_IN_RESTAURANT: 'Air Conditioning In Restaurant',
  POOL: 'Pool',
  HAS_24_HOUR_FRONT_DESK: 'Has 24 Hour Front Desk',
  CURRENCY_EXCHANGE: 'Currency Exchange',
  TOURS: 'Tours',
  AQUA_FIT: 'Aqua Fit',
  OUTDOOR_POOL: 'Outdoor Pool',
  GOLF: 'Golf',
  BRUNCH: 'Brunch',
  FAMILY_ROOM: 'Family Room',
  NEWSPAPER_IN_LOBBY: 'Newspaper In Lobby',
  CONFERENCE_HOSTESS: 'Conference Hostess',
  CHILDREN_POOL: 'Children Pool',
  HAIR_SALON: 'Hair Salon',
  CARPARK: 'Carpark',
  TELEVISION: 'Television',
  ELEVATOR: 'Elevator',
  SPA_TUB: 'Spa Tub',
  OUTDOOR_FRESHWATER_POOL: 'Outdoor Freshwater Pool',
  OUTDOOR_TENNIS_COURT: 'Outdoor Tennis Court',
  FISHING: 'Fishing',
  HEATER: 'Heater',
  FRONT_DESK: 'Front Desk',
  BREAKFAST_BUFFET: 'Breakfast Buffet',
  SAFETY_DEPOSIT_BOX: 'Safety Deposit Box',
  GOLF_PRACTICE_FACILITY: 'Golf Practice Facility',
  CRIBS: 'CRIBS',
  PROJECTOR: 'Projector',
  SPECIAL_DIETARY_OPTIONS: 'Special Dietary Options',
  PHOTOCOPIER: 'Photocopier',
  THEATRE_OR_AUDITORIUM: 'Theatre Or Auditorium',
  CONNECTING_ROOMS: 'Connecting Rooms',
  AIR_CONDITIONING: 'Air Conditioning',
  EXPRESS_CHECK_IN: 'Express Check In',
  MEDICAL_SERVICE: 'Medical Service',
  CRUISE_SHUTTLE: 'Cruise Shuttle',
  THEME_PARK_SHUTTLE: 'Theme Park Shuttle',
  COFFEE_SHOP: 'Coffee Shop',
  FIREPLACE_IN_LOBBY: 'Fireplace In Lobby',
  LATE_RISER_BREAKFAST: 'Late Riser Breakfast',
  FULL_BOARD_WITH_NON_ALCOHOLIC_DRINKS: 'Full Board With Non Alcoholic Drinks',
  RESTAURANT: 'Restaurant',
  ACCESSIBILITY_EQUIPMENT: 'Accessibility Equipment',
  HALF_BOARD_WITH_DRINKS: 'Half Board With Drinks',
  SHOPPING_CENTER_SHUTTLE: 'Shopping Center Shuttle',
  COMPUTER_STATION: 'Computer Station',
  CASINO_SHUTTLE_SURCHARGE: 'Casino Shuttle Surcharge',
  BASKETBALL: 'Basketball',
  DESK: 'Desk',
  TABLE_TENNIS: 'Table Tennis',
  WATER_PARK_ACCESS: 'Water Park Access',
  WINERY: 'Winery',
  GAME_ROOM: 'Game Room',
  HOT_TUB: 'Hot Tub',
  MINI_GOLF: 'Mini Golf',
  CONCIERGE: 'Concierge',
  COFFEE_OR_TEA_IN_LOBBY: 'Coffee Or Tea In Lobby',
  REFRIGERATOR: 'Refrigerator',
  BREAKFAST_AND_DINNER: 'Breakfast And Dinner',
  HEALTH_CLUB: 'Health Club',
  MARINA: 'Marina',
  CONTINENTAL_BREAKFAST: 'Continental Breakfast',
  RESTAURANT_FOR_LUNCH: 'Restaurant For Lunch',
  WIFI_PUBLIC_AREA_SURCHARGE: 'Wifi Public Area Surcharge',
  COMPLIMENTARY_RECEPTION: 'Complimentary Reception',
  WHEELCHAIR_ACCESSIBLE: 'Wheelchair Accessible',
  INTERNET_POINT: 'Internet Point',
  GROCERY: 'Grocery',
  BICYCLE_HIRE_SERVICE: 'Bicycle Hire Service',
  SHOPS: 'Shops',
  EARLY_BIRD_BREAKFAST: 'Early Bird Breakfast',
  INDOOR_FRESHWATER_POOL: 'Indoor Freshwater Pool',
  HAS_24_HOUR_ROOM_SERVICE: 'Has 24 Hour Room Service',
  BEACH_BAR: 'Beach Bar',
  CABLE_TV: 'Cable Tv',
  HIGHCHAIRS: 'Highchairs',
  DOORMAN: 'Doorman',
  WATERSKIING: 'Waterskiing',
  KARAOKE: 'Karaoke',
  HALF_BOARD_WITHOUT_DRINKS: 'Half Board Without Drinks',
  LARGE_PETS_ALLOWED: 'Large Pets Allowed',
  WIFI_PUBLIC_AREA: 'Wifi Public Area',
  LATE_CHECK_OUT: 'Late Check Out',
  GOLF_DESK: 'Golf Desk',
  SHOW_COOKING: 'Show Cooking',
  CASINO_SHUTTLE: 'Casino Shuttle',
  ENTERTAINMENT_PROGRAMME_FOR_CHILDREN: 'Entertainment Programme For Children',
  EARLY_CHECKIN: 'Early Checkin',
  ACCESSIBLE_BATHROOM: 'Accessible Bathroom',
  GALA_DINNER: 'Gala Dinner',
  A_LA_CARTE_BREAKFAST: 'A La Carte Breakfast',
  SAFARI: 'Safari',
  GARDEN: 'Garden',
  BREAKFAST_AND_LUNCH: 'Breakfast And Lunch',
  GOLF_COURSE: 'Golf Course',
  PUB: 'Pub',
  BARBECUE_GRILL: 'Barbecue Grill',
  WIFI_SURCHARGE: 'Wifi Surcharge',
  AREA_SHUTTLE_SURCHARGE: 'Area Shuttle Surcharge',
  CHILDREN_CLUB: 'Children Club',
  RESTAURANT_FOR_DINNER: 'Restaurant For Dinner',
  TRAIN_STATION_PICKUP: 'Train Station Pickup',
  PARASOL: 'Parasol',
  SKI: 'Ski',
  BANQUET: 'Banquet',
  NEWSPAPER_STAND: 'Newspaper Stand',
  BUFFET_LUNCH: 'Buffet Lunch',
  LAN_INTERNET_ACCESS: 'Lan Internet Access',
  CYCLING_OR_MOUNTAIN_BIKING: 'Cycling Or Mountain Biking',
  SQUASH: 'Squash',
  POOL_SUN_LOUNGERS: 'Pool Sun Loungers',
  FITNESS_CENTER: 'Fitness Center',
  ARCHERY: 'Archery',
  LAN_INTERNET_ACCESS_SURCHARGE: 'Lan Internet Access Surcharge',
  HORSE_RIDING: 'Horse Riding',
  IN_ROOM_SAFE: 'In Room Safe',
  PETS_ALLOWED: 'Pets Allowed',
  MOTOR_BOARD_RIDE: 'Motor Board Ride',
  BATHTUB: 'Bathtub',
  SAUNA: 'Sauna',
  MEETING_FACILITIES: 'Meeting Facilities',
  BUSINESS_CENTER: 'Business Center',
  DAYCARE_CENTRE: 'Daycare Centre',
  BEAUTY_SALON: 'Beauty Salon',
  SPORT_COURT: 'Sport Court',
  HALF_BOARD_WITH_NON_ALCOHOLIC_DRINKS: 'Half Board With Non Alcoholic Drinks',
  SOLARIUM: 'Solarium',
  WATER_SPORT: 'Water Sport',
  CARPARK_SURCHARGE: 'Carpark Surcharge',
  LIMO_OR_TOWN_CAR_SERVICE: 'Limo Or Town Car Service',
  LIMITED_HOURS_ROOM_SERVICE: 'Limited Hours Room Service',
  ROLL_IN_SHOWER: 'Roll In Shower',
  NIGHTCLUB: 'Nightclub',
  ACCESSIBLE_PARKING: 'Accessible Parking',
  LAUNDERETTE: 'Launderette',
  SET_MENU_LUNCH: 'Set Menu Lunch',
  SUPERMARKET: 'Supermarket',
  POOL_CABANAS: 'Pool Cabanas',
  FULL_BOARD_WITH_DRINKS: 'Full Board With Drinks',
  CAR_HIRE: 'Car Hire',
  SKI_STORAGE: 'Ski Storage',
  ACCESS_FRIENDLY: 'Access Friendly',
  ACCESSIBLE_PATH_OF_TRAVEL: 'Accessible Path Of Travel',
  JET_SKI: 'Jet Ski',
  ENTERTAINMENT_PROGRAMME_FOR_ADULTS: 'Entertainment Programme For Adults',
  BREAKFAST: 'Breakfast',
  BATHROBE: 'Bathrobe',
  WINDSURFING: 'Windsurfing',
  RECREATION_ROOM: 'Recreation Room',
  SUPERVISED_CHILDCARE: 'Supervised Childcare',
  BEACH_TOWEL: 'Beach Towel',
  SMOKING_AREA: 'Smoking Area',
  BUFFET_DINNER: 'Buffet Dinner',
  AIRPORT_TRANSFER_SURCHARGE: 'Airport Transfer Surcharge',
  SMALL_PETS_ALLOWED: 'Small Pets Allowed',
  PADDLE_TENNIS: 'Paddle Tennis',
  DVD_PLAYER: 'Dvd Player',
  EARLY_CHECK_IN: 'Early Check In',
  SKI_SHUTTLE: 'Ski Shuttle',
  PRIVATE_BEACH_NEARBY: 'Private Beach Nearby',
  BADMINTON: 'Badminton',
  LUGGAGE_STORAGE: 'Luggage Storage',
  SECURE_PARKING: 'Secure Parking',
  PEDAL_BOATING: 'Pedal Boating',
  STEAMROOM: 'Steamroom',
  BEACH_CABANAS: 'Beach Cabanas',
  ROOM_SERVICE: 'Room Service',
  DARTS: 'Darts',
  A_LA_CARTE_DINNER: 'A La Carte Dinner',
  CARPARK_LIMITED: 'Carpark Limited',
  TURKISH_BATH: 'Turkish Bath',
  BANANA_BOATING: 'Banana Boating',
  NO_ALCOHOL_IS_SERVED: 'No Alcohol Is Served',
  OUTDOOR_SALTWATER_POOL: 'Outdoor Saltwater Pool',
  GIFT_SHOP: 'Gift Shop',
  FERRY_TERMINAL_SHUTTLE_SURCHARGE: 'Ferry Terminal Shuttle Surcharge',
  AEROBICS: 'Aerobics',
  BOWLING_ALLEY: 'Bowling Alley',
  GLUTEN_FREE_MEALS: 'Gluten Free Meals',
  SET_MENU_DINNER: 'Set Menu Dinner',
  MOBILE: 'Mobile',
  SNACK_BAR: 'Snack Bar',
  CAFE: 'Cafe',
  FITNESS: 'Fitness',
  IN_ROOM_ACCESSIBILITY: 'In Room Accessibility',
  BEACH_SHUTTLE: 'Beach Shuttle',
  SPA: 'Spa',
  WATER_PARK_ACCESS_SURCHARGE: 'Water Park Access Surcharge',
  SMOKING_FREE: 'Smoking Free',
  DIVING: 'Diving',
  BEACH_VOLLEYBALL: 'Beach Volleyball',
  MASSAGE: 'Massage',
  BRAILLE_OR_RAISED_SIGNAGE: 'Braille Or Raised Signage',
  AREA_SHUTTLE: 'Area Shuttle',
  SAILING: 'Sailing',
  CLOAKROOM: 'Cloakroom',
  OUTDOOR_HEATED_POOL: 'Outdoor Heated Pool',
  CANOEING: 'Canoeing',
  STEAM_BATH: 'Steam Bath',
  PRIVATE_BEACH: 'Private Beach',
  VALET_PARKING: 'Valet Parking',
  BABYSITTING: 'Babysitting',
  TENNIS: 'Tennis',
  SECRETARIAL_SERVICE: 'Secretarial Service',
  LAUNDRY_SERVICE: 'Laundry Service',
  TRANSFER_SERVICE: 'Transfer Service',
  POOLSIDE_BAR: 'Poolside Bar',
  CRUISE_SHUTTLE_SURCHARGE: 'Cruise Shuttle Surcharge',
  SNORKELING: 'Snorkeling',
  DISCOUNTED_FITNESS_CENTER: 'Discounted Fitness Center',
  TERRACE: 'Terrace',
  ROOFTOP_TERRACE: 'Rooftop Terrace',
  BILLIARDS: 'Billiards',
  PICNIC_AREA: 'Picnic Area',
  BEACH_SUN_LOUNGERS: 'Beach Sun Loungers',
  VEGETARIAN_MEAL: 'Vegetarian Meal',
  RV_BUS_TRUCK_PARKING: 'Rv Bus Truck Parking',
  THEME_PARK_SHUTTLE_SURCHARGE: 'Theme Park Shuttle Surcharge',
  VALET_PARKING_SURCHARGE: 'Valet Parking Surcharge',
  SURFING: 'Surfing',
  BOCCE: 'Bocce',
  SKI_SHUTTLE_SURCHARGE: 'Ski Shuttle Surcharge',
  LATE_CHECKOUT: 'Late Checkout',
  GARAGE: 'Garage',
  BREAKFAST_SURCHARGE: 'Breakfast Surcharge',
  PARKING_AREA: 'Parking Area',
  BALLROOM: 'Ballroom',
  MULTILINGUAL_STAFF: 'Multilingual Staff',
  SHOWER: 'Shower',
  AIRPORT_TRANSFER: 'Airport Transfer',
  KITCHENETTE: 'Kitchenette',
  HOT_BREAKFAST: 'Hot Breakfast',
  FERRY_TERMINAL_SHUTTLE: 'Ferry Terminal Shuttle',
  MICROWAVE: 'Microwave',
  CONFERENCE_ROOM: 'Conference Room',
  CLOTHES_DRYER: 'Clothes Dryer',
  POOL_OR_SNOOKER: 'Pool Or Snooker',
  PORTER: 'Porter',
  EXPRESS_CHECK_OUT: 'Express Check Out',
  SNACKS: 'Snacks',
  SWIMUP_BAR: 'Swimup Bar',
  BAR: 'Bar',
  PRINTER: 'Printer',
  INDOOR_TENNIS_COURT: 'Indoor Tennis Court',
  RESTAURANT_FOR_BREAKFAST: 'Restaurant For Breakfast',
  BICYCLE_STORAGE: 'Bicycle Storage',
  ATM_OR_BANKING: 'Atm Or Banking',
  CASINO: 'Casino',
  CHILDREN_CLUB_SURCHARGE: 'Children Club Surcharge',
};
