export const dataRoomFacilities = [
  {
    id: 1,
    name: 'room_laundry',
    include: {
      INTERNET_ACCESS_WIFI_CHARGES_APPLY: 'Internet Access Wifi Charges Apply',
      HAIR_DRYER: 'Hair Dryer',
      DISHWASHER: 'Dishwasher',
      INTERNET_ACCESS_LAN_CHARGES_APPLY: 'Internet Access Lan Charges Apply',
      IN_ROOM_SAFE: 'In Room Safe',
      MOSQUITO_NET: 'Mosquito Net',
      CLOTHES_DRYER: 'Clothes Dryer',
      AIR_CONDITIONING: 'Air Conditioning',
      IRONING_FACILITIES: 'Ironing Facilities',
      MICROWAVE: 'Microwave',
      INTERNET_ACCESS_WIFI_COMPLIMENTARY: 'Internet Access Wifi Complimentary',
      WASHING_MACHINE: 'Washing Machine',
      BLACKOUT_CURTAINS: 'Blackout Curtains',
      DESK: 'Desk',
      INTERNET_ACCESS_LAN_COMPLIMENTARY: 'Internet Access Lan Complimentary',
      FAN: 'Fan',
    },
  },
  {
    id: 2,
    name: 'food_drinks',
    include: {
      COMPLIMENTARY_BOTTLED_WATER: 'Complimentary Bottled Water',
      MINI_BAR: 'Mini Bar',
      REFRIGERATOR: 'Refrigerator',
      COFFEE_TEA_MAKER: 'Coffee Tea Maker',
      BREAKFAST: 'Breakfast',
      LUNCH: 'Lunch',
      DINNER: 'Dinner',
    },
  },
  {
    id: 3,
    name: 'entertainment',
    include: {
      DAILY_NEWSPAPER: 'Daily Newspaper',
      INHOUSE_MOVIES: 'Inhouse Movies',
      IN_ROOM_VIDEO_GAMES: 'In Room Video Games',
      TELEVISION: 'Television',
      DVD_CD_PLAYER: 'Dvd Cd Player',
    },
  },
  {
    id: 4,
    name: 'room_configuration_access',
    include: {
      SHARED_BATHROOM: 'Shared Bathroom',
      BALCONY_TERRACE: 'Balcony Terrace',
      KITCHENETTE: 'Kitchenette',
      NON_SMOKING_ROOMS: 'Non Smoking Rooms',
      EXECUTIVE_LOUNGE_ACCESS: 'Executive Lounge Access',
      SEATING_AREA: 'Seating Area',
      SEPARATE_DINING_AREA: 'Separate Dining Area',
      INTERCONNECTING_ROOMS_AVAILABLE: 'Interconnecting Rooms Available',
    },
  },
  {
    id: 5,
    name: 'bathroom_pool',
    include: {
      DAILY_NEWSPAPER: 'Daily Newspaper',
      INHOUSE_MOVIES: 'Inhouse Movies',
      IN_ROOM_VIDEO_GAMES: 'In Room Video Games',
      TELEVISION: 'Television',
      DVD_CD_PLAYER: 'Dvd Cd Player',
    },
  },
];
