export const dataPropertyFacilities = [
  {
    id: 1,
    name: 'common',
    include: {
      PARKING_AREA: 'Parking Area',
      ROOM_SERVICE: 'Room Service',
      SAFETY_DEPOSIT_BOX: 'Safety Deposit Box',
      WIFI_PUBLIC_AREA: 'Wifi Public Area',
      COFFEE_SHOP: 'Coffee Shop',
      RESTAURANT: 'Restaurant',
      COFFEE_OR_TEA_IN_LOBBY: 'Coffee Or Tea In Lobby',
      ELEVATOR: 'Elevator',
      RESTAURANT_FOR_BREAKFAST: 'Restaurant For Breakfast',
      RESTAURANT_FOR_LUNCH: 'Restaurant For Lunch',
      RESTAURANT_FOR_DINNER: 'Restaurant For Dinner',
      LATE_CHECKOUT: 'Late Checkout',
      EARLY_CHECKIN: 'Early Checkin',
    },
  },
  {
    id: 2,
    name: 'accessibility',
    include: {
      ACCESSIBLE_BATHROOM: 'Accessible Bathroom',
      ACCESSIBLE_PARKING: 'Accessible Parking',
      ACCESSIBLE_PATH_OF_TRAVEL: 'Accessible Path Of Travel',
      IN_ROOM_ACCESSIBILITY: 'In Room Accessibility',
      ROLL_IN_SHOWER: 'Roll In Shower',
      BRAILLE_OR_RAISED_SIGNAGE: 'Braille Or Raised Signage',
      ACCESSIBILITY_EQUIPMENT: 'Accessibility Equipment',
      WHEELCHAIR_ACCESSIBLE: 'Wheelchair Accessible',
      ACCESS_FRIENDLY: 'Access Friendly',
    },
  },
  {
    id: 3,
    name: 'business',
    include: {
      BUSINESS_CENTER: 'Business Center',
      MEETING_FACILITIES: 'Meeting Facilities',
      COMPUTER_STATION: 'Computer Station',
      SECRETARIAL_SERVICE: 'Secretarial Service',
      CONFERENCE_ROOM: 'Conference Room',
      PROJECTOR: 'Projector',
      CONFERENCE_HOSTESS: 'Conference Hostess',
      PHOTOCOPIER: 'Photocopier',
      THEATRE_OR_AUDITORIUM: 'Theatre Or Auditorium',
      BUSINESS_FACILITY: 'Business Facility',
      PRINTER: 'Printer',
    },
  },
  {
    id: 4,
    name: 'connectivity',
    include: {
      WIFI_SURCHARGE: 'Wifi Surcharge',
      WIFI_FREE: 'Wifi Free',
      LAN_INTERNET_ACCESS: 'Lan Internet Access',
      LAN_INTERNET_ACCESS_SURCHARGE: 'Lan Internet Access Surcharge',
      WIFI_PUBLIC_AREA_SURCHARGE: 'Wifi Public Area Surcharge',
      INTERNET_POINT: 'Internet Point',
      INTERNATIONAL_CALL: 'International Call',
    },
  },
  {
    id: '5',
    name: 'facilities',
    include: {
      FAMILY_ROOM: 'Family Room',
      SMOKING_AREA: 'Smoking Area',
      AIR_CONDITIONING: 'Air Conditioning',
      NON_SMOKING_ROOM: 'Non Smoking Room',
      TERRACE: 'Terrace',
      FIREPLACE_IN_LOBBY: 'Fireplace In Lobby',
      BALLROOM: 'Ballroom',
      BANQUET: 'Banquet',
      CLOAKROOM: 'Cloakroom',
      CLOTHES_DRYER: 'Clothes Dryer',
      CONNECTING_ROOMS: 'Connecting Rooms',
      SMOKING_FREE: 'Smoking Free',
      HEATER: 'Heater',
      ROOFTOP_TERRACE: 'Rooftop Terrace',
      RECREATION_ROOM: 'Recreation Room',
      POOL: 'Pool',
    },
  },
  {
    id: 6,
    name: 'food_drinks',
    include: {
      WINERY: 'Winery',
      BEACH_BAR: 'Beach Bar',
      BAR: 'Bar',
      NIGHTCLUB: 'Nightclub',
      POOLSIDE_BAR: 'Poolside Bar',
      SNACK_BAR: 'Snack Bar',
      BREAKFAST: 'Breakfast',
      BREAKFAST_SURCHARGE: 'Breakfast Surcharge',
      SHOW_COOKING: 'Show Cooking',
      AIR_CONDITIONING_IN_RESTAURANT: 'Air Conditioning In Restaurant',
      CAFE: 'Cafe',
      PUB: 'Pub',
      SET_MENU_DINNER: 'Set Menu Dinner',
      BREAKFAST_AND_DINNER: 'Breakfast And Dinner',
      SNACKS: 'Snacks',
      BREAKFAST_AND_LUNCH: 'Breakfast And Lunch',
      SPECIAL_DIETARY_OPTIONS: 'Special Dietary Options',
      EARLY_BIRD_BREAKFAST: 'Early Bird Breakfast',
      LATE_RISER_BREAKFAST: 'Late Riser Breakfast',
      HOT_BREAKFAST: 'Hot Breakfast',
      BREAKFAST_SERVED_TO_THE_TABLE: 'Breakfast Served To The Table',
      BRUNCH: 'Brunch',
      GLUTEN_FREE_MEALS: 'Gluten Free Meals',
      NO_ALCOHOL_IS_SERVED: 'No Alcohol Is Served',
      VEGETARIAN_MEAL: 'Vegetarian Meal',
      HALF_BOARD_WITHOUT_DRINKS: 'Half Board Without Drinks',
      HALF_BOARD_WITH_NON_ALCOHOLIC_DRINKS:
        'Half Board With Non Alcoholic Drinks',
      HALF_BOARD_WITH_DRINKS: 'Half Board With Drinks',
      FULL_BOARD_WITHOUT_DRINKS: 'Full Board Without Drinks',
      FULL_BOARD_WITH_NON_ALCOHOLIC_DRINKS:
        'Full Board With Non Alcoholic Drinks',
      FULL_BOARD_WITH_DRINKS: 'Full Board With Drinks',
      BREAKFAST_BUFFET: 'Breakfast Buffet',
      A_LA_CARTE_BREAKFAST: 'A La Carte Breakfast',
      CONTINENTAL_BREAKFAST: 'Continental Breakfast',
      BUFFET_LUNCH: 'Buffet Lunch',
      A_LA_CARTE_LUNCH: 'A La Carte Lunch',
      SET_MENU_LUNCH: 'Set Menu Lunch',
      BUFFET_DINNER: 'Buffet Dinner',
      A_LA_CARTE_DINNER: 'A La Carte Dinner',
      GALA_DINNER: 'Gala Dinner',
      DINING_AREA: 'Dining Area',
    },
  },
  {
    id: 7,
    name: 'inside_room',
    include: {
      BATHROBE: 'Bathrobe',
      BATHTUB: 'Bathtub',
      DESK: 'Desk',
      REFRIGERATOR: 'Refrigerator',
      HAIR_DRYER: 'Hair Dryer',
      IN_ROOM_SAFE: 'In Room Safe',
      TELEVISION: 'Television',
      SHOWER: 'Shower',
      SEPARATE_SHOWER_AND_TUB: 'Separate Shower And Tub',
      MINIBAR: 'Minibar',
      MICROWAVE: 'Microwave',
      KITCHENETTE: 'Kitchenette',
      CABLE_TV: 'Cable Tv',
      DVD_PLAYER: 'Dvd Player',
    },
  },
  {
    id: 8,
    name: 'nearby_amenities',
    include: {
      GIFT_SHOP: 'Gift Shop',
      SHOPS: 'Shops',
      ATM_OR_BANKING: 'Atm Or Banking',
      HAIR_SALON: 'Hair Salon',
      GROCERY: 'Grocery',
      SUPERMARKET: 'Supermarket',
      LAUNDERETTE: 'Launderette',
      BEAUTY_SALON: 'Beauty Salon',
    },
  },
  {
    id: 9,
    name: 'service',
    include: {
      FRONT_DESK: 'Front Desk',
      CONCIERGE: 'Concierge',
      LAUNDRY_SERVICE: 'Laundry Service',
      TOURS: 'Tours',
      HAS_24_HOUR_FRONT_DESK: 'Has 24 Hour Front Desk',
      LUGGAGE_STORAGE: 'Luggage Storage',
      PORTER: 'Porter',
      LIMITED_HOURS_ROOM_SERVICE: 'Limited Hours Room Service',
      NEWSPAPER_IN_LOBBY: 'Newspaper In Lobby',
      MULTILINGUAL_STAFF: 'Multilingual Staff',
      WEDDING_SERVICE: 'Wedding Service',
      EXPRESS_CHECK_IN: 'Express Check In',
      EXPRESS_CHECK_OUT: 'Express Check Out',
      COMPLIMENTARY_RECEPTION: 'Complimentary Reception',
      EARLY_CHECK_IN: 'Early Check In',
      LATE_CHECK_OUT: 'Late Check Out',
      CURRENCY_EXCHANGE: 'Currency Exchange',
      DOORMAN: 'Doorman',
      MOBILE: 'Mobile',
      MEDICAL_SERVICE: 'Medical Service',
      HAS_24_HOUR_SECURITY: 'Has 24 Hour Security',
      BELLBOY_SERVICE: 'Bellboy Service',
      NEWSPAPER_STAND: 'Newspaper Stand',
    },
  },

  {
    id: 10,
    name: 'sports_recreation',
    include: {
      SKI: 'Ski',
      SKI_STORAGE: 'Ski Storage',
      BILLIARDS: 'Billiards',
      OUTDOOR_TENNIS_COURT: 'Outdoor Tennis Court',
      TENNIS: 'Tennis',
      GAME_ROOM: 'Game Room',
      GOLF_COURSE: 'Golf Course',
      INDOOR_TENNIS_COURT: 'Indoor Tennis Court',
      GOLF_DESK: 'Golf Desk',
      BANANA_BOATING: 'Banana Boating',
      WATERSKIING: 'Waterskiing',
      JET_SKI: 'Jet Ski',
      MOTOR_BOARD_RIDE: 'Motor Board Ride',
      DIVING: 'Diving',
      WINDSURFING: 'Windsurfing',
      SAILING: 'Sailing',
      CANOEING: 'Canoeing',
      CATAMARAN_SAILING: 'Catamaran Sailing',
      PEDAL_BOATING: 'Pedal Boating',
      TABLE_TENNIS: 'Table Tennis',
      SQUASH: 'Squash',
      AEROBICS: 'Aerobics',
      FITNESS: 'Fitness',
      ARCHERY: 'Archery',
      HORSE_RIDING: 'Horse Riding',
      CYCLING_OR_MOUNTAIN_BIKING: 'Cycling Or Mountain Biking',
      HANDBALL: 'Handball',
      BASKETBALL: 'Basketball',
      VOLLEYBALL: 'Volleyball',
      BEACH_VOLLEYBALL: 'Beach Volleyball',
      POOL_OR_SNOOKER: 'Pool Or Snooker',
      BOCCE: 'Bocce',
      BOWLING_ALLEY: 'Bowling Alley',
      MINI_GOLF: 'Mini Golf',
      GOLF: 'Golf',
      SURFING: 'Surfing',
      PADDLE_TENNIS: 'Paddle Tennis',
      BADMINTON: 'Badminton',
      DARTS: 'Darts',
      GOLF_PRACTICE_FACILITY: 'Golf Practice Facility',
      SAFARI: 'Safari',
      AQUA_FIT: 'Aqua Fit',
      FISHING: 'Fishing',
      SPORT_COURT: 'Sport Court',
      WATER_SPORT: 'Water Sport',
      SNORKELING: 'Snorkeling',
    },
  },

  {
    id: 11,
    name: 'things_to_do',
    include: {
      CHILDREN_CLUB_SURCHARGE: 'Children Club Surcharge',
      WATER_PARK_ACCESS_SURCHARGE: 'Water Park Access Surcharge',
      MASSAGE: 'Massage',
      HOT_TUB: 'Hot Tub',
      FITNESS_CENTER: 'Fitness Center',
      STEAMROOM: 'Steamroom',
      SPA: 'Spa',
      OUTDOOR_POOL: 'Outdoor Pool',
      GARDEN: 'Garden',
      HEALTH_CLUB: 'Health Club',
      SAUNA: 'Sauna',
      SPA_TUB: 'Spa Tub',
      CHILDREN_POOL: 'Children Pool',
      POOL_CABANAS: 'Pool Cabanas',
      BARBECUE_GRILL: 'Barbecue Grill',
      PICNIC_AREA: 'Picnic Area',
      CHILDREN_CLUB: 'Children Club',
      POOL_SUN_LOUNGERS: 'Pool Sun Loungers',
      BEACH_SUN_LOUNGERS: 'Beach Sun Loungers',
      BEACH_TOWEL: 'Beach Towel',
      BEACH_UMBRELLA: 'Beach Umbrella',
      LIBRARY: 'Library',
      PRIVATE_BEACH: 'Private Beach',
      PRIVATE_BEACH_NEARBY: 'Private Beach Nearby',
      TURKISH_BATH: 'Turkish Bath',
      INDOOR_POOL: 'Indoor Pool',
      WATERSLIDE: 'Waterslide',
      DISCOUNTED_FITNESS_CENTER: 'Discounted Fitness Center',
      BEACH_CABANAS: 'Beach Cabanas',
      MARINA: 'Marina',
      WATER_PARK_ACCESS: 'Water Park Access',
      SWIMUP_BAR: 'Swimup Bar',
      CASINO: 'Casino',
      TV_LOUNGE: 'Tv Lounge',
      CHILDREN_PLAY_AREA: 'Children Play Area',
      INDOOR_FRESHWATER_POOL: 'Indoor Freshwater Pool',
      INDOOR_HEATED_POOL: 'Indoor Heated Pool',
      OUTDOOR_FRESHWATER_POOL: 'Outdoor Freshwater Pool',
      OUTDOOR_SALTWATER_POOL: 'Outdoor Saltwater Pool',
      OUTDOOR_HEATED_POOL: 'Outdoor Heated Pool',
      SUN_LOUNGERS: 'Sun Loungers',
      PARASOL: 'Parasol',
      ENTERTAINMENT_PROGRAMME_FOR_ADULTS: 'Entertainment Programme For Adults',
      ENTERTAINMENT_PROGRAMME_FOR_CHILDREN:
        'Entertainment Programme For Children',
      SOLARIUM: 'Solarium',
      STEAM_BATH: 'Steam Bath',
      KARAOKE: 'Karaoke',
      OUTDOOR_ACTIVITIES: 'Outdoor Activities',
    },
  },
  {
    id: 12,
    name: 'transportation',
    include: {
      SKI_SHUTTLE: 'Ski Shuttle',
      SKI_SHUTTLE_SURCHARGE: 'Ski Shuttle Surcharge',
      CASINO_SHUTTLE: 'Casino Shuttle',
      CASINO_SHUTTLE_SURCHARGE: 'Casino Shuttle Surcharge',
      CRUISE_SHUTTLE: 'Cruise Shuttle',
      CRUISE_SHUTTLE_SURCHARGE: 'Cruise Shuttle Surcharge',
      SHOPPING_CENTER_SHUTTLE_SURCHARGE: 'Shopping Center Shuttle Surcharge',
      THEME_PARK_SHUTTLE: 'Theme Park Shuttle',
      THEME_PARK_SHUTTLE_SURCHARGE: 'Theme Park Shuttle Surcharge',
      AIRPORT_TRANSFER: 'Airport Transfer',
      VALET_PARKING: 'Valet Parking',
      VALET_PARKING_SURCHARGE: 'Valet Parking Surcharge',
      AIRPORT_TRANSFER_SURCHARGE: 'Airport Transfer Surcharge',
      CARPARK_SURCHARGE: 'Carpark Surcharge',
      SHOPPING_CENTER_SHUTTLE: 'Shopping Center Shuttle',
      CARPARK_LIMITED: 'Carpark Limited',
      AREA_SHUTTLE_SURCHARGE: 'Area Shuttle Surcharge',
      BEACH_SHUTTLE: 'Beach Shuttle',
      AREA_SHUTTLE: 'Area Shuttle',
      RV_BUS_TRUCK_PARKING: 'Rv Bus Truck Parking',
      TRAIN_STATION_PICKUP: 'Train Station Pickup',
      LIMO_OR_TOWN_CAR_SERVICE: 'Limo Or Town Car Service',
      BICYCLE_STORAGE: 'Bicycle Storage',
      BICYCLE_HIRE_SERVICE: 'Bicycle Hire Service',
      GARAGE: 'Garage',
      CAR_HIRE: 'Car Hire',
      TRANSFER_SERVICE: 'Transfer Service',
      SECURE_PARKING: 'Secure Parking',
      FERRY_TERMINAL_SHUTTLE: 'Ferry Terminal Shuttle',
      FERRY_TERMINAL_SHUTTLE_SURCHARGE: 'Ferry Terminal Shuttle Surcharge',
    },
  },

  {
    id: 13,
    name: 'traveling_with_others',
    include: {
      BABYSITTING: 'Babysitting',
      SUPERVISED_CHILDCARE: 'Supervised Childcare',
      BABYSITTING_SURCHARGE: 'Babysitting Surcharge',
      PETS_ALLOWED: 'Pets Allowed',
      DAYCARE_CENTRE: 'Daycare Centre',
      SMALL_PETS_ALLOWED: 'Small Pets Allowed',
      LARGE_PETS_ALLOWED: 'Large Pets Allowed',
      HIGHCHAIRS: 'Highchairs',
      CRIBS: 'CRIBS',
    },
  },
];
